#!/bin/bash
sudo hdparm -I /dev/sda | grep -w 'Model Number:'
sudo hdparm -I /dev/sda | grep -w 'Serial Number:'
sudo hdparm -I /dev/sda | grep -w 'Firmware Revision:'
sudo hdparm -I /dev/sda | grep -w 'Transport:'
sudo hdparm -I /dev/sda | grep -w 'Supported:' | grep -v 'Enabled'
sudo hdparm -I /dev/sda | grep -w 'PIO:'
sudo hdparm -I /dev/sda | grep -w 'DMA:'
df -hT
